name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'reaviz/reaviz'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          version: 12.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      # - name: Lint
      #  run: yarn lint

      - name: Build Prod
        run: yarn build

      - name: Build Storybook
        run: yarn build-storybook

      - name: Test
        run: yarn test -- --runInBand --no-cache --coverage

      # - name: Create Release Pull Request or Publish to npm
      #  uses: changesets/action@master
      #  with:
      #    publish: yarn release
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
