name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'reaviz/reaviz'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          version: 12.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Build Storybook
        run: yarn build-storybook

      - name: Copy Domain
        run: yarn copy

      - name: Publish Storybook to GH Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: storybook-static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Chromatic
        run: yarn chromatic

      # - name: Create Release Pull Request or Publish to npm
      #  uses: changesets/action@master
      #  with:
      #    publish: yarn release
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
